version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user
    ports:
      - "3307:3306"
    networks:
      - rePick
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app1:
    image: repick_user:latest
    container_name: app1_container
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_PASSWORD: root_password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rePick

networks:
  rePick: