version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_HOST: mysql:3307
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user
    ports:
      - "3307:3306"
    networks:
      - rePick_network

  app1:
    image: repick_user:latest
    environment:
      SPRING_PROFILES_ACTIVE: production
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - rePick_network

networks:
  rePick_network: