spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/user?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:aaaaaaaa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
jwt:
  secret-key: 4Ixa3PT4KhLW1fz4bJoY8z2dR4Gk7jHpB3Yw8mQvL9NdXx5vT9Yw8VhN3rB4YxK2
  ACCESS_TOKEN_MINUTE_TIME: 30
  REFRESH_TOKEN_MINUTE_TIME: 60
kakao:
  client-id: 425177266f9081ed665e51bd34048cc9
  redirect-uri: http://localhost:8080/api/v1/oauth/kakao/callback
  #client-secret: NXgY4VhOyaYJ1IaJsospn8laSzGzYo5n
  #client-id: 26aa2297f0431d7a130b7f937f10eb4c
  token-url: https://kauth.kakao.com/oauth/token
naver:
  client-id: A_aQx4dtFzTavl7L6lVf
  client-secret: LCXsU5_Skl
  redirect-uri: http://localhost:8080/api/v1/oauth/naver/callback