spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/user?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:aaaaaaaa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  secret-key: 4Ixa3PT4KhLW1fz4bJoY8z2dR4Gk7jHpB3Yw8mQvL9NdXx5vT9Yw8VhN3rB4YxK2

kakao:
  #client-id: 425177266f9081ed665e51bd34048cc9
  #client-secret: NXgY4VhOyaYJ1IaJsospn8laSzGzYo5n
  client-id: 26aa2297f0431d7a130b7f937f10eb4c
  redirect-uri: http://localhost:8080/api/oauth/kakao/callback
  token-url: https://kauth.kakao.com/oauth/token
